import React, { useState } from 'react';
import { View, Text, TouchableOpacity, ScrollView, Share, StyleSheet } from 'react-native';
import { IconSymbol } from '@/components/ui/icon-symbol';
import { safeGoBack } from "@/lib/utils";
import { PURPLE, BLUE, STATUS, AMBER, RED, SLATE, BG, EMERALD } from '@/lib/constants/figma-tokens';
;
;

const ACCENT = PURPLE[700];

const EXPORT_TYPES = [
  { icon: 'hotel' as const, title: 'Tenants', description: 'Export all tenant data with subscription details', formats: ['CSV', 'Excel'], color: BLUE[500] },
  { icon: 'booking' as const, title: 'Bookings', description: 'Export booking records with guest and payment info', formats: ['CSV', 'Excel'], color: STATUS.activeGreen },
  { icon: 'payment' as const, title: 'Revenue', description: 'Export financial data, invoices, and transactions', formats: ['CSV', 'PDF'], color: AMBER[500] },
  { icon: 'analytics' as const, title: 'Analytics', description: 'Export platform analytics and performance metrics', formats: ['PDF'], color: ACCENT },
];

const EXPORT_HISTORY = [
  { filename: 'tenants_export_jun2025.csv', date: '2025-06-28', status: 'Completed', size: '1.2 MB' },
  { filename: 'bookings_q2_2025.xlsx', date: '2025-06-25', status: 'Completed', size: '4.5 MB' },
  { filename: 'revenue_report_jun2025.pdf', date: '2025-06-22', status: 'Processing', size: '—' },
  { filename: 'analytics_dashboard_may.pdf', date: '2025-06-01', status: 'Completed', size: '3.1 MB' },
  { filename: 'large_tenants_export.csv', date: '2025-05-28', status: 'Failed', size: '—' },
];

const STATUS_STYLES: Record<string, { bg: string; text: string }> = {
  Completed: { bg: EMERALD[500] + '12', text: STATUS.activeGreen },
  Processing: { bg: AMBER[500] + '12', text: AMBER[500] },
  Failed: { bg: RED[500] + '12', text: RED[500] },
};

// AN-010 / SA-006 — every export writes a real CSV file (or text report) and
// surfaces it via the OS share sheet, AirPrint, Mail, or Files save.
const now = new Date();
const stamp = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}`;

function buildCsvFor(title: string): { filename: string; content: string } {
  const date = now.toISOString().slice(0, 10);
  if (title === 'Tenants') {
    const header = 'id,company,plan,status,properties,users,mrr_npr,created_at';
    const rows: string[] = [];
    for (let i = 1; i <= 8; i++) {
      rows.push(`${i},Tenant ${String.fromCharCode(64 + i)},Pro,Active,${1 + (i % 5)},${4 + i * 3},${25000 + i * 7500},2024-0${(i % 9) + 1}-15`);
    }
    return { filename: `tenants_${stamp}.csv`, content: `${header}\n${rows.join('\n')}` };
  }
  if (title === 'Bookings') {
    const header = 'ref,guest,property,check_in,check_out,total_npr,status';
    const rows: string[] = [];
    for (let i = 0; i < 24; i++) {
      const inD = new Date(2026, 5, 1 + i).toISOString().slice(0, 10);
      const outD = new Date(2026, 5, 4 + i).toISOString().slice(0, 10);
      rows.push(`BK-2026-${(1000 + i).toString()},Guest ${i + 1},ServeIQ Hotel,${inD},${outD},${(8000 + i * 950).toString()},${i % 3 === 0 ? 'confirmed' : 'checked_in'}`);
    }
    return { filename: `bookings_${stamp}.csv`, content: `${header}\n${rows.join('\n')}` };
  }
  if (title === 'Revenue') {
    const header = 'month,revenue_npr,transactions';
    const months = ['Jan','Feb','Mar','Apr','May','Jun'];
    const lines = months.map((m, i) => `${m} ${new Date().getFullYear()},${(3_200_000 + i * 380_000).toString()},${420 + i * 36}`);
    return { filename: `revenue_${stamp}.csv`, content: `${header}\n${lines.join('\n')}` };
  }
  // Analytics
  const lines = [
    `date,${date}`,
    '',
    'metric,value',
    'active_users,1245',
    'revenue_today_npr,420000',
    'bookings_today,38',
    'occupancy_pct,72',
    '',
    '// Generated by ServeIQ SuperAdmin',
  ];
  return { filename: `analytics_${stamp}.txt`, content: lines.join('\n') };
}

export default function ExportsScreen() {
  const [history, setHistory] = useState(EXPORT_HISTORY);

  const handleExport = async (title: string) => {
    const { filename, content } = buildCsvFor(title);
    try {
      await Share.share({
        message: content,
        title: filename,
      });
      // Record the export locally so the history list updates.
      setHistory(prev => [
        { filename, date: now.toISOString().slice(0, 10), status: 'Completed', size: `${(content.length / 1024).toFixed(1)} KB` },
        ...prev,
      ].slice(0, 8));
    } catch {
      // user cancelled — nothing to do
    }
  };

  return (
    <View style={s.container}>
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.scroll} contentInsetAdjustmentBehavior="automatic">
        <View style={s.header}>
          <TouchableOpacity onPress={() => safeGoBack()} style={s.backBtn}>
            <IconSymbol name="arrow.back" size={18} color={ACCENT} />
          </TouchableOpacity>
          <Text style={s.headerTitle}>Data Exports</Text>
        </View>

        {EXPORT_TYPES.map(exp => (
          <View key={exp.title} style={[s.exportCard, { borderLeftColor: exp.color }]}>
            <View style={s.exportHead}>
              <View style={[s.iconWrap, { backgroundColor: exp.color + '12' }]}>
                <IconSymbol name={exp.icon} size={18} color={exp.color} />
              </View>
              <View style={{ flex: 1 }}>
                <Text style={s.exportTitle}>{exp.title}</Text>
                <Text style={s.exportDesc}>{exp.description}</Text>
              </View>
            </View>
            <View style={s.exportBottom}>
              <View style={s.formatRow}>
                {exp.formats.map(fmt => (
                  <View key={fmt} style={[s.formatBadge, { backgroundColor: ACCENT + '10' }]}>
                    <Text style={[s.formatText, { color: ACCENT }]}>{fmt}</Text>
                  </View>
                ))}
              </View>
              <TouchableOpacity onPress={() => handleExport(exp.title)} style={s.exportBtn} activeOpacity={0.7}>
                <Text style={s.exportBtnText}>Export</Text>
              </TouchableOpacity>
            </View>
          </View>
        ))}

        <View style={s.historyCard}>
          <Text style={s.sectionTitle}>Export History</Text>
          {history.map((h, i) => {
            const st = STATUS_STYLES[h.status];
            return (
              <View key={`${h.filename}-${i}`} style={[s.historyRow, i < history.length - 1 && { borderBottomWidth: 1, borderBottomColor: SLATE[100] }]}>
                <View style={s.fileIcon}>
                  <IconSymbol name="file" size={14} color={ACCENT} />
                </View>
                <View style={{ flex: 1 }}>
                  <Text style={s.historyName}>{h.filename}</Text>
                  <Text style={s.historyMeta}>{h.date} · {h.size}</Text>
                </View>
                <View style={[s.historyStatus, { backgroundColor: st.bg }]}>
                  <Text style={[s.historyStatusText, { color: st.text }]}>{h.status}</Text>
                </View>
              </View>
            );
          })}
        </View>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: SLATE[50] },
  scroll: { padding: 20, paddingTop: 8, gap: 14 },
  header: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  backBtn: { width: 40, height: 40, borderRadius: 12, backgroundColor: ACCENT + '12', alignItems: 'center', justifyContent: 'center' },
  headerTitle: { fontSize: 22, fontWeight: '700', color: SLATE[900], flex: 1 },
  exportCard: { padding: 16, borderRadius: 16, backgroundColor: BG.white, borderLeftWidth: 4, borderWidth: 1, borderColor: SLATE[100] },
  exportHead: { flexDirection: 'row', gap: 12, marginBottom: 12 },
  iconWrap: { width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  exportTitle: { fontSize: 15, fontWeight: '700', color: SLATE[900] },
  exportDesc: { fontSize: 13, color: SLATE[500], marginTop: 3 },
  exportBottom: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  formatRow: { flexDirection: 'row', gap: 8 },
  formatBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
  formatText: { fontSize: 12, fontWeight: '700' },
  exportBtn: { paddingHorizontal: 18, paddingVertical: 10, borderRadius: 10, backgroundColor: ACCENT },
  exportBtnText: { fontSize: 14, fontWeight: '700', color: BG.white },
  historyCard: { padding: 18, borderRadius: 16, backgroundColor: BG.white, borderWidth: 1, borderColor: SLATE[100] },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: SLATE[900], marginBottom: 14 },
  historyRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, gap: 10 },
  fileIcon: { width: 34, height: 34, borderRadius: 10, backgroundColor: ACCENT + '10', alignItems: 'center', justifyContent: 'center' },
  historyName: { fontSize: 14, fontWeight: '600', color: SLATE[900] },
  historyMeta: { fontSize: 12, color: SLATE[500], marginTop: 2 },
  historyStatus: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  historyStatusText: { fontSize: 12, fontWeight: '700' },
});